Database-build:



Database-migrate:


image-build:
docker build --tag wm-back-end .

docker-tag:
docker tag wm-back-end hansbukerg/wm-back-end

image-push:
docker push hansbukerg/wm-back-end

fly-create:
flyctl launch

fly-push:
flyctl deploy

image-run:
docker run -d -p 8080:8080 --name wm-back-end wm-back-end

this-works:
go test ./... -coverprofile=cover.txt
go tool cover -html=cover

